### ISSUE TITLE
database update operations are missing await

### ISSUE THREAD

**Issue by saurik** [asadamatic/Daily-Todo#1]
Yo! I was just reading an answer by you on StackOverflow about usage of ChangeNotifier+FutureBuilder where you referenced your code, and so I was glancing at your queries just now... I'm not 100% sure, but I'm like _pretty sure_, that you should be using await before your operations such as db.delete in LocalDatabase.dart; the issue is that your method--which is async--calls db.delete() and then immediately calls notifyListeners(), but the operation (which at least will have begun AFAIK, as dart futures are eager) might not have completed by the time the notification happens, as db.delete is (I'm pretty sure) async. In practice it probably works almost all of the time, but I don't think "because it is correct". Regardless: just wanted to make sure I wasn't the asshole who saw a bug in code from someone who helped me and then just _didn't try to help back_ ;P.

**Comment by asadamatic** [comment]
Thanks, @saurik , I realized this mistake only now, when I was updating the project for my portfolio.
